### PR TITLE
fix deprecated class usage

### PR DESCRIPTION
**Pull request by deminy**
This includes changes from PR #11 , along with additional changes for class \derhasi\Composer\PluginWrapper. Tested with Composer 1.3.1 (latest stable release).

### CODE REVIEW

**Comment by leymannx** [comment]
Merge, merge, merge! Merge, merge, merge!

**Comment by derhasi** [comment]
I am currently improving tests for the project and then will merge this.

**Comment by derhasi** [comment]
@deminy, you changed the namespaces to `deminy`, so I cannot use your PR :(
I also will add phpcs first in #14

**Comment by deminy** [comment]
@derhasi I recently started to use Composer to manage my Drupal 7 modules and noticed this module very helpful. However, the main problem was that it didn't support wildcard pattern matching. Since my PR was not accepted in time, I changed the namespace to _deminy_ today. I will change it back if this PR will accepted. Please allow one to two days before I change it back. Thanks

**Comment by deminy** [comment]
I guess I have changed the namespace back. :)

**Comment by derhasi** [comment]
@deminy I had to rebase your initial changes and added them to a new PR in #17 

For the rest of your changes you made in that branch, please open separate new PRs. I then can have a closer look.

Thanks for your patience.

**Comment by derhasi** [comment]
The inital commits were now merged with #17 
Thanks @deminy

**Pull request closed without merging**
